read:
  mode: "proto"
  proto:
      pathToDescriptor: "path_to_descriptor"
  subject: "*"

server:
  port: 1111

logging:
  level:
    otterjet.monitoring.NatsMonitoringApiClient: DEBUG

nats:
  server:
#    monitoring:      # Optional, monitoring needs to be enabled in the nats server
#      port: 8222
#      protocol: "http"
    host: "localhost"
    port: 4222