read:
  mode: "proto"
  proto:
      pathToDescriptor: "path_to_descriptor"
  subject: "*"
  store:
    limit: 1000
#  startDate: "2020-01-01T00:00:00Z" # format is "yyyy-MM-dd'T'HH:mm:ss'Z'"

server:
  port: 1111

logging:
  level:
    otter.jet.monitoring.NatsMonitoringApiClient: DEBUG

nats:
  server:
#    monitoring:      # Optional, monitoring needs to be enabled in the nats server
#      port: 8222
#      protocol: "http"
    host: "localhost"
    port: 4222